-- Run in Supabase SQL Editor. Custom JWT auth is enforced by the trusted Express API.
create extension if not exists "pgcrypto";
create table users(id uuid primary key default gen_random_uuid(),name text not null,email text not null unique,password_hash text not null,role text not null default 'user' check(role in('user','admin')),avatar_url text,style_preferences jsonb default '[]',created_at timestamptz default now(),updated_at timestamptz default now());
create table categories(id uuid primary key default gen_random_uuid(),name text not null unique,description text,image_url text,created_at timestamptz default now());
create table products(id uuid primary key default gen_random_uuid(),name text not null,description text,brand text not null,category_id uuid references categories(id) on delete restrict,subcategory text,image_url text,additional_images jsonb default '[]',price numeric(10,2) not null check(price>=0),original_price numeric(10,2),discount_percentage integer default 0,color text,secondary_color text,size_options jsonb default '[]',style text,occasion text,season text,gender text,stock integer default 0,is_active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table outfits(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,name text not null,description text,image_url text,occasion text,style text,created_at timestamptz default now(),updated_at timestamptz default now());
create table outfit_items(id uuid primary key default gen_random_uuid(),outfit_id uuid not null references outfits(id) on delete cascade,product_id uuid not null references products(id) on delete restrict,item_type text,created_at timestamptz default now());
create table wishlists(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,product_id uuid not null references products(id) on delete cascade,created_at timestamptz default now(),unique(user_id,product_id));
create table deals(id uuid primary key default gen_random_uuid(),product_id uuid not null references products(id) on delete cascade,discount_percentage integer not null check(discount_percentage between 0 and 100),old_price numeric(10,2) not null,new_price numeric(10,2) not null,start_date timestamptz not null,end_date timestamptz not null,is_active boolean default true,created_at timestamptz default now());
create table notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references users(id) on delete cascade,title text not null,message text not null,type text,is_read boolean default false,created_at timestamptz default now());
create index products_search_idx on products using gin(to_tsvector('english',coalesce(name,'')||' '||coalesce(brand,'')||' '||coalesce(color,'')));create index products_category_idx on products(category_id);create index wishlists_user_idx on wishlists(user_id);create index notifications_user_idx on notifications(user_id);
alter table users enable row level security;alter table categories enable row level security;alter table products enable row level security;alter table outfits enable row level security;alter table outfit_items enable row level security;alter table wishlists enable row level security;alter table deals enable row level security;alter table notifications enable row level security;
-- No public policies: custom backend JWTs are not Supabase Auth JWTs. Service-role calls bypass RLS; Express authorization is mandatory.
-- Create private bucket product-images in Storage. The backend uploads with service role and creates URLs; never expose that key to browsers.
